-- Traduz os valores de status e nivel que aparecem no banco.
-- Primeiro cada coluna aceita valores antigos e novos, depois os registros sao convertidos.

ALTER TABLE `academias` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO';
UPDATE `academias` SET `status` = CASE `status` WHEN 'ACTIVE' THEN 'ATIVO' WHEN 'INACTIVE' THEN 'INATIVO' ELSE `status` END;
ALTER TABLE `academias` MODIFY `status` ENUM('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO';

ALTER TABLE `usuarios` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO';
UPDATE `usuarios` SET `status` = CASE `status` WHEN 'ACTIVE' THEN 'ATIVO' WHEN 'INACTIVE' THEN 'INATIVO' ELSE `status` END;
ALTER TABLE `usuarios` MODIFY `status` ENUM('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO';

ALTER TABLE `funcionarios` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO';
UPDATE `funcionarios` SET `status` = CASE `status` WHEN 'ACTIVE' THEN 'ATIVO' WHEN 'INACTIVE' THEN 'INATIVO' ELSE `status` END;
ALTER TABLE `funcionarios` MODIFY `status` ENUM('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO';

ALTER TABLE `planos` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'ATIVO', 'INATIVO') NOT NULL;
UPDATE `planos` SET `status` = CASE `status` WHEN 'ACTIVE' THEN 'ATIVO' WHEN 'INACTIVE' THEN 'INATIVO' ELSE `status` END;
ALTER TABLE `planos` MODIFY `status` ENUM('ATIVO', 'INATIVO') NOT NULL;

ALTER TABLE `alunos` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'ATIVO', 'INATIVO') NOT NULL;
UPDATE `alunos` SET `status` = CASE `status` WHEN 'ACTIVE' THEN 'ATIVO' WHEN 'INACTIVE' THEN 'INATIVO' ELSE `status` END;
ALTER TABLE `alunos` MODIFY `status` ENUM('ATIVO', 'INATIVO') NOT NULL;

ALTER TABLE `matriculas` MODIFY `status` ENUM('ACTIVE', 'EXPIRED', 'CANCELED', 'ATIVO', 'EXPIRADO', 'CANCELADO') NOT NULL DEFAULT 'ATIVO';
UPDATE `matriculas` SET `status` = CASE `status` WHEN 'ACTIVE' THEN 'ATIVO' WHEN 'EXPIRED' THEN 'EXPIRADO' WHEN 'CANCELED' THEN 'CANCELADO' ELSE `status` END;
ALTER TABLE `matriculas` MODIFY `status` ENUM('ATIVO', 'EXPIRADO', 'CANCELADO') NOT NULL DEFAULT 'ATIVO';

ALTER TABLE `formas_pagamento` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO';
UPDATE `formas_pagamento` SET `status` = CASE `status` WHEN 'ACTIVE' THEN 'ATIVO' WHEN 'INACTIVE' THEN 'INATIVO' ELSE `status` END;
ALTER TABLE `formas_pagamento` MODIFY `status` ENUM('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO';

ALTER TABLE `pagamentos` MODIFY `status` ENUM('PENDING', 'PAID', 'OVERDUE', 'CANCELED', 'PENDENTE', 'PAGO', 'ATRASADO', 'CANCELADO') NOT NULL DEFAULT 'PENDENTE';
UPDATE `pagamentos` SET `status` = CASE `status` WHEN 'PENDING' THEN 'PENDENTE' WHEN 'PAID' THEN 'PAGO' WHEN 'OVERDUE' THEN 'ATRASADO' WHEN 'CANCELED' THEN 'CANCELADO' ELSE `status` END;
ALTER TABLE `pagamentos` MODIFY `status` ENUM('PENDENTE', 'PAGO', 'ATRASADO', 'CANCELADO') NOT NULL DEFAULT 'PENDENTE';

ALTER TABLE `treinos` MODIFY `level` ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'INICIANTE', 'INTERMEDIARIO', 'AVANCADO') NOT NULL;
UPDATE `treinos` SET `level` = CASE `level` WHEN 'BEGINNER' THEN 'INICIANTE' WHEN 'INTERMEDIATE' THEN 'INTERMEDIARIO' WHEN 'ADVANCED' THEN 'AVANCADO' ELSE `level` END;
ALTER TABLE `treinos` MODIFY `level` ENUM('INICIANTE', 'INTERMEDIARIO', 'AVANCADO') NOT NULL;

ALTER TABLE `treinos` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'COMPLETED', 'ATIVO', 'INATIVO', 'CONCLUIDO') NOT NULL DEFAULT 'ATIVO';
UPDATE `treinos` SET `status` = CASE `status` WHEN 'ACTIVE' THEN 'ATIVO' WHEN 'INACTIVE' THEN 'INATIVO' WHEN 'COMPLETED' THEN 'CONCLUIDO' ELSE `status` END;
ALTER TABLE `treinos` MODIFY `status` ENUM('ATIVO', 'INATIVO', 'CONCLUIDO') NOT NULL DEFAULT 'ATIVO';

ALTER TABLE `exercicios` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO';
UPDATE `exercicios` SET `status` = CASE `status` WHEN 'ACTIVE' THEN 'ATIVO' WHEN 'INACTIVE' THEN 'INATIVO' ELSE `status` END;
ALTER TABLE `exercicios` MODIFY `status` ENUM('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO';

ALTER TABLE `registros_frequencia` MODIFY `source` ENUM('MANUAL', 'CLASS', 'CHECK_IN', 'AULA', 'ENTRADA') NOT NULL DEFAULT 'MANUAL';
UPDATE `registros_frequencia` SET `source` = CASE `source` WHEN 'CLASS' THEN 'AULA' WHEN 'CHECK_IN' THEN 'ENTRADA' ELSE `source` END;
ALTER TABLE `registros_frequencia` MODIFY `source` ENUM('MANUAL', 'AULA', 'ENTRADA') NOT NULL DEFAULT 'MANUAL';

ALTER TABLE `tipos_aula` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO';
UPDATE `tipos_aula` SET `status` = CASE `status` WHEN 'ACTIVE' THEN 'ATIVO' WHEN 'INACTIVE' THEN 'INATIVO' ELSE `status` END;
ALTER TABLE `tipos_aula` MODIFY `status` ENUM('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO';

ALTER TABLE `horarios_aula` MODIFY `status` ENUM('SCHEDULED', 'COMPLETED', 'CANCELED', 'AGENDADO', 'CONCLUIDO', 'CANCELADO') NOT NULL DEFAULT 'AGENDADO';
UPDATE `horarios_aula` SET `status` = CASE `status` WHEN 'SCHEDULED' THEN 'AGENDADO' WHEN 'COMPLETED' THEN 'CONCLUIDO' WHEN 'CANCELED' THEN 'CANCELADO' ELSE `status` END;
ALTER TABLE `horarios_aula` MODIFY `status` ENUM('AGENDADO', 'CONCLUIDO', 'CANCELADO') NOT NULL DEFAULT 'AGENDADO';

ALTER TABLE `inscricoes_aula` MODIFY `status` ENUM('ENROLLED', 'CANCELED', 'ATTENDED', 'MISSED', 'INSCRITO', 'CANCELADO', 'PRESENTE', 'AUSENTE') NOT NULL DEFAULT 'INSCRITO';
UPDATE `inscricoes_aula` SET `status` = CASE `status` WHEN 'ENROLLED' THEN 'INSCRITO' WHEN 'CANCELED' THEN 'CANCELADO' WHEN 'ATTENDED' THEN 'PRESENTE' WHEN 'MISSED' THEN 'AUSENTE' ELSE `status` END;
ALTER TABLE `inscricoes_aula` MODIFY `status` ENUM('INSCRITO', 'CANCELADO', 'PRESENTE', 'AUSENTE') NOT NULL DEFAULT 'INSCRITO';

ALTER TABLE `equipamentos` MODIFY `status` ENUM('ACTIVE', 'MAINTENANCE', 'INACTIVE', 'ATIVO', 'MANUTENCAO', 'INATIVO') NOT NULL DEFAULT 'ATIVO';
UPDATE `equipamentos` SET `status` = CASE `status` WHEN 'ACTIVE' THEN 'ATIVO' WHEN 'MAINTENANCE' THEN 'MANUTENCAO' WHEN 'INACTIVE' THEN 'INATIVO' ELSE `status` END;
ALTER TABLE `equipamentos` MODIFY `status` ENUM('ATIVO', 'MANUTENCAO', 'INATIVO') NOT NULL DEFAULT 'ATIVO';

ALTER TABLE `manutencoes_equipamentos` MODIFY `status` ENUM('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELED', 'AGENDADO', 'EM_ANDAMENTO', 'CONCLUIDO', 'CANCELADO') NOT NULL DEFAULT 'AGENDADO';
UPDATE `manutencoes_equipamentos` SET `status` = CASE `status` WHEN 'SCHEDULED' THEN 'AGENDADO' WHEN 'IN_PROGRESS' THEN 'EM_ANDAMENTO' WHEN 'COMPLETED' THEN 'CONCLUIDO' WHEN 'CANCELED' THEN 'CANCELADO' ELSE `status` END;
ALTER TABLE `manutencoes_equipamentos` MODIFY `status` ENUM('AGENDADO', 'EM_ANDAMENTO', 'CONCLUIDO', 'CANCELADO') NOT NULL DEFAULT 'AGENDADO';

ALTER TABLE `metas` MODIFY `status` ENUM('ACTIVE', 'ACHIEVED', 'CANCELED', 'ATIVO', 'ALCANCADO', 'CANCELADO') NOT NULL DEFAULT 'ATIVO';
UPDATE `metas` SET `status` = CASE `status` WHEN 'ACTIVE' THEN 'ATIVO' WHEN 'ACHIEVED' THEN 'ALCANCADO' WHEN 'CANCELED' THEN 'CANCELADO' ELSE `status` END;
ALTER TABLE `metas` MODIFY `status` ENUM('ATIVO', 'ALCANCADO', 'CANCELADO') NOT NULL DEFAULT 'ATIVO';
